#### Numpy

- NumPy is fundamental library for scientific computing in Python.
- it provides support for arrays and matrices, along with a collection of mathematica function to operate on  these data structures.

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

## Create array using numpy

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
print(arr.shape) # Output: (5,) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])

# Reshape the array to (1, 5) means 1 row and 5 columns (array becomes two dimensions)
arr1.reshape((1, 5))

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D Array

arr2 = np.array(
    [
        [1, 2, 3, 4, 5], 
        [4, 5, 6, 7, 8],
    ]
)

print(arr2)
print(arr2.shape) # Output: (2, 5)  # 2 rows and 5 columns

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)


In [ ]:
np.arange(0, 10, 2) # creates array from 0 to 10 element with 2 step size -> [0, 2, 4, 6, 8]

array([0, 2, 4, 6, 8])

In [11]:
np.ones((3, 4)) # creates 3x4 array with all elements as 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## Attributes of NumPy

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("Array: \n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Number of dimensions: 2
Size (number of elements): 8
Data type: int64
Item size (in bytes): 8


##### NumPy Vectorized Operation

In [ ]:

arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([10,20,30,40,50,60,70])

# Element-wise addition
print("Addition:", arr1 + arr2)

# Element-wise substraction
print("Substraction:", arr1 - arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55 66 77]
Substraction: [ -9 -18 -27 -36 -45 -54 -63]
Multiplication: [ 10  40  90 160 250 360 490]
Division: [0.1 0.1 0.1 0.1 0.1 0.1 0.1]


##### Universal Function

In [ ]:
# Universal Functions (ufuncs) are functions that operate element-wise on arrays. They are optimized for performance and can be used to perform mathematical operations on entire arrays without the need for explicit loops.


arr = np.array([2, 3, 4, 5, 6])

# square root
print("Square Root:", np.sqrt(arr))

# Exponential
print("Exponential:", np.exp(arr))

# Sine
print("Sine:", np.sin(arr))

# natural logarithm
print("Natural Logarithm:", np.log(arr))

Square Root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural Logarithm: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


##### Array slicing and indexing

In [30]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original Array: \n", arr)


print("Element at [0, 0]:", arr[0, 0])

print("Element at [1, 3]:", arr[1, 3])

# print 3, 4, 7, 8 elements
print(arr[0, 2:4])
print(arr[1, 2:4])

Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at [0, 0]: 1
Element at [1, 3]: 8
[3 4]
[7 8]


In [ ]:
# pick up 6, 7, 10, 11 elements
print(arr[1:, 1:3])

# 1: -> means all the elements from 1 row, till the last

[[ 6  7]
 [10 11]]


##### Modify array elements

In [32]:
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Practical Examples

In [ ]:
## Statistical concepts - Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

# output -
# Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [38]:
# Calculating Mean, Median, Standard deviation, variance

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median 5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


#### Logical operations

In [45]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


print(data > 5) # Output - [False False False False False  True  True  True  True  True]

print(data[data > 5]) # Output - [ 6  7  8  9 10]

print(data[(data >= 5) & (data <= 8)]) # Output - [5 6 7 8]

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
